spring:
  profiles: default
  datasource:
    url: jdbc:mysql://localhost:3306/note-db?useSSL=false
    username: note-user
    password: note-password
    platform: mysql
    initialize: true
    schema: classpath:/scripts/schema.sql
    data: classpath:/scripts/data.sql
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

# Make the application available at http://localhost:8082
server:
  port: 8084
  contextPath: /services

# Configure the User Info Resource Server details
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:9090/auth/user
  basic:
    enabled: false
    
logging:
  level:
    org.springframework.security: info

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
---

spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://oauth2:3306/note-db?useSSL=false
    username: note-user
    password: note-password
    platform: mysql
    initialize: true
    schema: classpath:/scripts/schema.sql
    data: classpath:/scripts/data.sql
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    #hibernate:
      #ddl-auto: update
    show-sql: true
    
# Make the application available at http://localhost:8081/services
server:
  port: 8084
  contextPath: /services

# Configure the User Info Resource Server details
security:
  oauth2:
    resource:
      user-info-uri: http://auth-server:9090/auth/user
  basic:
    enabled: false
    
logging:
  level:
    org.springframework.security: info

