spring:
  profiles: default
  datasource:
    url: jdbc:mysql://192.168.56.10:3306/oauth2-db?useSSL=false
    username: oauth2-user
    password: oauth2-password
    platform: mysql
    initialize: true
    schema: classpath:/scripts/schema.sql
    data: classpath:/scripts/data.sql
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    #hibernate:
      #ddl-auto: update
    show-sql: true

# Make the application available at http://localhost:8081
server:
  port: 8082
  contextPath: /services

# Configure the User Info Resource Server details
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:9090/auth/user
  basic:
    enabled: false
    
logging:
  level:
    org.springframework.security: info

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
---

spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://oauth2:3306/oauth2-db?useSSL=false
    username: oauth2-user
    password: oauth2-password
    platform: mysql
    initialize: true
    schema: classpath:/scripts/schema.sql
    data: classpath:/scripts/data.sql
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    #hibernate:
      #ddl-auto: update
    show-sql: true
    
# Make the application available at http://localhost:8081/services
server:
  port: 8082
  contextPath: /services

# Configure the User Info Resource Server details
security:
  oauth2:
    resource:
      user-info-uri: http://auth-server:9090/auth/user
  basic:
    enabled: false
    
logging:
  level:
    org.springframework.security: info

